/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppView: typeof import('./main/views/AppView.vue')['default']
    DragBox: typeof import('./main/views/DragBox.vue')['default']
    HeaderArea: typeof import('./main/views/HeaderArea.vue')['default']
    HomeView: typeof import('./main/views/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingView: typeof import('./main/views/SettingView.vue')['default']
  }
}
