/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GroupCard: typeof import('./main/views/GroupCard.vue')['default']
    HeaderArea: typeof import('./common/HeaderArea.vue')['default']
    HomeSearch: typeof import('./main/views/HomeSearch.vue')['default']
    HomeView: typeof import('./main/views/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingView: typeof import('./settings/views/SettingView.vue')['default']
  }
}
